grafana:
  enabled: true

alertmanager:
  enabled: false

kubeStateMetrics:
  enabled: true

nodeExporter:
  enabled: true

prometheus:
  prometheusSpec:
    retention: 6h
    resources:
      requests:
        memory: 512Mi
      limits:
        memory: 1Gi
    serviceMonitorNamespaceSelector: {}
    serviceMonitorSelector:
      matchLabels:
        release: monitoring
